Nodes = ["127.0.0.1:7171"]

[HTTPServer]
  Addr = "127.0.0.1:7171"

[HTTPClient]
  Dial = 1000000000
  KeepAlive = 120000000000

[Env]
  Region = "china"
  Zone = "gd"
  Host = "test"
  DeployEnv = "dev"

[Schedulers]
  [Schedulers."test.service-dev"]
    AppID = "test.service"
    Env = "dev"
    Remark = "test"

    [[Schedulers."test.service-dev".Zones]]
      Src = "gd"
      [Schedulers."test.service-dev".Zones.Dst]
        sz01 = 3
